### ISSUE TITLE
use SD card instead of flash

### ISSUE THREAD

**Issue by jiangotto** [BojanJurca/Esp32_web_ftp_telnet_server_template#12]
The flash is too small,only 4MB.I'm wondering if we can use SD card filesystem,but i can't make it.Do you have any plans to support SD filesystem. :)

**Comment by BojanJurca** [comment]
I'll keep it in mind ...

**Comment by jiangotto** [comment]
> I'll keep it in mind ...

THANKS SO MUCH.
I've tried to edit parts of your code but there are something wrong with my code.I will keep debugging.

**Comment by BojanJurca** [comment]
Hi. 

Unfortunately, only recently I found the time to think about your suggestion. I do not think I can make a solution to your problem that would be generic enough to fit into the template since the template is about different kinds of servers whereas mounting SD card is all about file system.

In ESP32 you cannot mount a SD card to file system that deals with built in flash memory. A separate file system is mounted instead. Please look at: https://randomnerdtutorials.com/esp32-microsd-card-arduino/

But I would suggest you rewrite a part of template code – after all this is why it is called a template, it was meant to be adapted for each individual needs. The part of code you are looking for is function: 
'''
String __internalHttpRequestHandler__ (String& httpRequest, httpServer::wwwSessionParameters *wsp) 
'''
in webServer.hpp. The template code is:

'''
      String __internalHttpRequestHandler__ (String& httpRequest, httpServer::wwwSessionParameters *wsp) { 
        // check if HTTP request is file name or report error 404

        #ifdef __FILE_SYSTEM__
          if (__fileSystemMounted__) {

            int i = httpRequest.indexOf (' ', 4);
            if (i >= 0) {
              String fileName = httpRequest.substring (5, i);
              if (fileName == "") fileName = "index.html";
              fileName = __webServerHomeDirectory__ + fileName;
              if (!stristr ((char *) wsp->httpResponseHeaderFields.c_str (), (char *) "CONTENT-TYPE")) { // add Content-Type if it is not set yet
                     if (fileName.endsWith (".bmp"))                                wsp->setHttpResponseHeaderField ("Content-Type", "image/bmp");
                else if (fileName.endsWith (".css"))                                wsp->setHttpResponseHeaderField ("Content-Type", "text/css");
                else if (fileName.endsWith (".csv"))                                wsp->setHttpResponseHeaderField ("Content-Type", "text/csv");
                else if (fileName.endsWith (".gif"))                                wsp->setHttpResponseHeaderField ("Content-Type", "image/gif");
                else if (fileName.endsWith (".htm") || fileName.endsWith (".html")) wsp->setHttpResponseHeaderField ("Content-Type", "text/html");
                else if (fileName.endsWith (".jpg") || fileName.endsWith (".jpeg")) wsp->setHttpResponseHeaderField ("Content-Type", "image/jpeg");
                else if (fileName.endsWith (".js"))                                 wsp->setHttpResponseHeaderField ("Content-Type", "text/javascript");
                else if (fileName.endsWith (".json"))                               wsp->setHttpResponseHeaderField ("Content-Type", "application/json");
                else if (fileName.endsWith (".mpeg"))                               wsp->setHttpResponseHeaderField ("Content-Type", "video/mpeg");
                else if (fileName.endsWith (".pdf"))                                wsp->setHttpResponseHeaderField ("Content-Type", "application/pdf");
                else if (fileName.endsWith (".png"))                                wsp->setHttpResponseHeaderField ("Content-Type", "image/png");
                else if (fileName.endsWith (".tif") || fileName.endsWith (".tiff")) wsp->setHttpResponseHeaderField ("Content-Type", "image/tiff");
                else if (fileName.endsWith (".txt"))                                wsp->setHttpResponseHeaderField ("Content-Type", "text/plain");
                // ... add more if needed but Contet-Type can often be omitted without problems ...
              }
              File f = FFat.open (fileName.c_str (), FILE_READ);           
              if (f) {
                if (!f.isDirectory ()) {
                  #define BUFF_SIZE 2048
                  char *buff = (char *) malloc (BUFF_SIZE); // get 2 KB of memory from heap
                  if (buff) {
                    String httpHeader = "HTTP/1.1 " + wsp->httpResponseStatus + "\r\n" + wsp->httpResponseHeaderFields + "Content-Length:" + String (f.size ()) + "\r\n\r\n";
                    // debug: Serial.printf ("[" + __class__ + " debug] %s", httpHeader.c_str ());
                    if (httpHeader.length () > BUFF_SIZE - 2) { // there should normally be enough space, but check anyway
                      f.close ();
                      return "HTTP/1.1 500 Internal server error\r\nContent-Length:29\r\n\r\nError: HTTP header too large."; 
                    }
                    strcpy (buff, httpHeader.c_str ());
                    int i = strlen (buff);
                    while (f.available ()) {
                      *(buff + i++) = f.read ();
                      if (i == BUFF_SIZE) { wsp->connection->sendData ((char *) buff, BUFF_SIZE); i = 0; }
                    }
                    if (i) { wsp->connection->sendData (buff, i); }
                    free (buff);
                  } 
                  f.close ();
                  return ""; // success
                } // if file is a file, not a directory
                f.close ();
              } // if file is open
            }
          }
        #endif

        return "HTTP/1.1 404 Not found\r\nContent-Length:20\r\n\r\nPage does not exist."; // HTTP header and content
      }  
'''

You need to do three things:

First: mount SD card (in setup () from example).

Second: rewrite the following line so that the file name would contain full file path of the file on your SD card:

'''
fileName = __webServerHomeDirectory__ + fileName;
'''

Third: rewrite the following line so that it would open a file on SD card instead of FFat.

'''
File f = FFat.open (fileName.c_str (), FILE_READ);
'''

I hope it works.

**Comment by BojanJurca** [comment]
If you want to make use of __webServerHomeDirectory__ as well - it is obtained from /etc/passwd as a home directory of system user named webserver. You can change this simply by editing /etc/passwd with built in telnet vi editor.

**Comment by BojanJurca** [comment]
I'm closing this issue.

**Comment by BojanJurca** [comment]
I kept it in my mind for quite some time, as promised. Now it is possible to use a SD card instead of  or together with a built-in flash disk. Preferred option would be "instead of" since the file system would use less memory for itself this way.  

When you start a httpServer you can specify the server's root directory if it is different from /var/www/html.

**Comment by jiangotto** [comment]
Excellent work!
Thanks for your continual efforts on this project.
